language: generic

sudo: required 
services:
  - docker 

before_install: 
  - docker build -t mohammad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohammad/react-test npm test 

after_success:
  - docker build -t mohammad/multi-client ./client 
  - docker build -t mohammad/multi-nginx ./nginx 
  - docker build -t mohammad/multi-server ./server
  - docker build -t mohammad/multi-worker ./worker 


