language: generic

sudo: required 
services:
  - docker 

before_install: 
  - docker build -t mohammad18p/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohammad18p/react-test npm test 

after_success:
  - docker build -t mohammad18p/multi-client ./client 
  - docker build -t mohammad18p/multi-nginx ./nginx 
  - docker build -t mohammad18p/multi-server ./server
  - docker build -t mohammad18p/multi-worker ./worker

# take images and push them to docker hub 
# login to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push mohammad18p/multi-worker
  - docker push mohammad18p/multi-server
  - docker push mohammad18p/multi-client
  - docker push mohammad18p/multi-nginx